
if(Object_ID('dbo.TempPdsInbound') is not null)
	drop table dbo.TempPdsInbound
GO

CREATE TABLE [dbo].[TempPdsInbound]
(
	[RowID] [bigint] NOT NULL,
	[Pseudo NHS Number] [varchar](15) NULL,
	[Primary Care Provider] [varchar](8) NULL,
	[Primary Care Provider Business Effective From Date] [date] NULL,
	[Primary Care Provider Business Effective To Date] [date] NULL,
	[Reason for Removal] [varchar](50) NULL,
	[derCcgOfRegistration] [varchar](5) NULL,
	[derCurrentCcgOfRegistration] [varchar](5) NULL,
	[derIcbOfRegistration] [varchar](5) NULL,
	[derCurrentIcbOfRegistration] [varchar](5) NULL
)

GO

INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111112000', N'GP111', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111113000', N'GP111', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111114000', N'GP211', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111115000', N'GP212', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111116000', N'GP221', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111117000', N'GP222', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111118000', N'GP222', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111119000', N'GP122', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111120000', N'GP221', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111121000', N'GP112', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111122000', N'GP212', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111123000', N'GP222', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111124000', N'GP211', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111125000', N'GP222', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111126000', N'GP221', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111127000', N'GP111', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111128000', N'GP121', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111129000', N'GP222', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111130000', N'GP122', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111131000', N'GP121', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111132000', N'GP212', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111133000', N'GP221', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111134000', N'GP112', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111135000', N'GP222', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111136000', N'GP121', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111137000', N'GP122', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111138000', N'GP211', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111139000', N'GP121', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111140000', N'GP112', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111141000', N'GP212', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111142000', N'GP121', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111143000', N'GP212', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111144000', N'GP221', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111145000', N'GP121', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111146000', N'GP121', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111147000', N'GP212', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111148000', N'GP211', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111149000', N'GP111', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111150000', N'GP212', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111151000', N'GP121', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111152000', N'GP121', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111153000', N'GP121', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111154000', N'GP212', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111155000', N'GP112', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111156000', N'GP111', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111157000', N'GP222', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111158000', N'GP221', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111159000', N'GP122', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111160000', N'GP212', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111161000', N'GP212', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111162000', N'GP121', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111163000', N'GP112', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111164000', N'GP221', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111165000', N'GP222', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111166000', N'GP122', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111167000', N'GP112', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111168000', N'GP121', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111169000', N'GP112', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111170000', N'GP112', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111171000', N'GP221', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111172000', N'GP111', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111173000', N'GP112', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111174000', N'GP121', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111175000', N'GP211', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111176000', N'GP122', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111177000', N'GP121', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111178000', N'GP122', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111179000', N'GP212', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111180000', N'GP221', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111181000', N'GP222', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111182000', N'GP121', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111183000', N'GP211', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111184000', N'GP222', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111185000', N'GP221', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111186000', N'GP211', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111187000', N'GP111', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111188000', N'GP212', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111189000', N'GP222', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111190000', N'GP111', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111191000', N'GP221', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111192000', N'GP122', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111193000', N'GP112', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111194000', N'GP112', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111195000', N'GP211', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111196000', N'GP111', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111197000', N'GP122', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111198000', N'GP222', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111199000', N'GP222', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111200000', N'GP221', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111201000', N'GP212', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111202000', N'GP221', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111203000', N'GP111', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111204000', N'GP121', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111205000', N'GP111', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111206000', N'GP121', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111207000', N'GP112', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111208000', N'GP122', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111209000', N'GP121', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111210000', N'GP112', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111211000', N'GP122', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111212000', N'GP221', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111213000', N'GP211', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111214000', N'GP222', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111215000', N'GP211', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111216000', N'GP221', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')
INSERT [dbo].[TempPdsInbound] ([RowID], [Pseudo NHS Number], [Primary Care Provider], [Primary Care Provider Business Effective From Date], [Primary Care Provider Business Effective To Date], [Reason for Removal], [derCcgOfRegistration], [derCurrentCcgOfRegistration], [derIcbOfRegistration], [derCurrentIcbOfRegistration]) VALUES (14105257787, N'1111217000', N'GP222', CAST(N'2013-11-04' AS Date), NULL, NULL, N'08D', N'93C', N'Q71', N'QMJ')

TRUNCATE TABLE PDSDatas


INSERT INTO PDSDatas (PseudoNhsNumber, OrgCode, ID) 
select [Pseudo NHS Number], ODSCode, NEWID() from 
(
select [Pseudo NHS Number],[Primary Care Provider],cast ([derCurrentCcgOfRegistration] as varchar(8)) [derCurrentCcgOfRegistration],cast([derCurrentIcbOfRegistration] as varchar(8)) [derCurrentIcbOfRegistration] from TempPdsInbound
) d
unpivot(OdsCode for ODSRel in ([Primary Care Provider], [derCurrentCcgOfRegistration], [derCurrentIcbOfRegistration])) unpiv