# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: "Install .NET Core SDK"
  inputs:
    version: 9.x
    performMultiLevelLookup: true
    includePreviewVersions: true # Required for preview versions

- task: DotNetCoreCLI@2
  displayName: "Dotnet Restore"
  inputs:
    command: "restore"
    feedsToUse: "select"
    projects: "**/*.csproj"
    includeNuGetOrg: true

- task: DotNetCoreCLI@2
  displayName: "Dotnet Publish Portal (Development)"
  inputs:
    command: "publish"
    publishWebProjects: false
    projects: "**/ISL.ReIdentification.Portals.Server.csproj"
    arguments: "-o $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_publish_output_website_frontend_portal_development --configuration Development"
    zipAfterPublish: true
    modifyOutputPath: false

- task: DotNetCoreCLI@2
  displayName: "Dotnet Publish Portal (Test)"
  inputs:
    command: "publish"
    publishWebProjects: false
    projects: "**/ISL.ReIdentification.Portals.Server.csproj"
    arguments: "-o $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_publish_output_website_frontend_portal_test --configuration Test"
    zipAfterPublish: true
    modifyOutputPath: false

- task: DotNetCoreCLI@2
  displayName: "Dotnet Publish Portal (Production)"
  inputs:
    command: "publish"
    publishWebProjects: false
    projects: "**/ISL.ReIdentification.Portals.Server.csproj"
    arguments: "-o $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_publish_output_website_frontend_portal_release --configuration Release"
    zipAfterPublish: true
    modifyOutputPath: false

- task: DotNetCoreCLI@2
  displayName: "Dotnet Publish Management Portal (Development)"
  inputs:
    command: "publish"
    publishWebProjects: false
    projects: "**/ISL.ReIdentification.Configurations.Server.csproj"
    arguments: "-o $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_publish_output_website_management_portal_development --configuration Development"
    zipAfterPublish: true
    modifyOutputPath: false

- task: DotNetCoreCLI@2
  displayName: "Dotnet Publish Management Portal (Test)"
  inputs:
    command: "publish"
    publishWebProjects: false
    projects: "**/ISL.ReIdentification.Configurations.Server.csproj"
    arguments: "-o $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_publish_output_website_management_portal_test --configuration Test"
    zipAfterPublish: true
    modifyOutputPath: false

- task: DotNetCoreCLI@2
  displayName: "Dotnet Publish Management Portal (Production)"
  inputs:
    command: "publish"
    publishWebProjects: false
    projects: "**/ISL.ReIdentification.Configurations.Server.csproj"
    arguments: "-o $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_publish_output_website_management_portal_release --configuration Release"
    zipAfterPublish: true
    modifyOutputPath: false

- publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_publish_output_website_frontend_portal_development.zip
  displayName: 'Publish Artifact - frontend portal'
  artifact: drop-frontend-portal
#- publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_publish_output_website_frontend_portal_Test/*.zip
#  displayName: 'Publish Artifact - frontend portal (Test)'
#  artifact: drop-frontend-portal
#- publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_publish_output_website_frontend_portal_*/*.zip
#  displayName: 'Publish Artifact - frontend portal (Release)'
#  artifact: drop-frontend-portal
#- publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_publish_output_website_management_portal_Development/*.zip
#  displayName: 'Publish Artifact - management portal (Development)'
#  artifact: drop-management-portal
#- publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_publish_output_website_management_portal_*/*.zip
#  displayName: 'Publish Artifact - management portal (Test)'
#  artifact: drop-management-portal
#- publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_publish_output_website_management_portal_*/*.zip
#  displayName: 'Publish Artifact - management portal (Release)'
#  artifact: drop-management-portal