# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: "Dotnet Build (Portal)"
  inputs:
    command: 'build'
    projects: '**/ISL.ReIdentification.Portals.Server.csproj'
    arguments: --output $(System.DefaultWorkingDirectory)/publish_output_website_frontend_portal --configuration Release
    azureSubscription: 
- task: DotNetCoreCLI@2
  displayName: "Dotnet Publish Portal (Development)"
  inputs:
    command: "publish"
    publishWebProjects: false
    projects: "**/ISL.ReIdentification.Portals.Server.csproj"
    arguments: "-o $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_publish_output_website_frontend_portal --configuration Release"
    zipAfterPublish: true
    modifyOutputPath: false
- task: ArchiveFiles@2
  displayName: 'Archive files - Portal'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/publish_output_website_frontend_portal'
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId)_publish_output_website_frontend_portal
    replaceExistingArchive: true