import { Agreement } from "../agreementCatalogue"

export const agreement_v0_1 = () => {
    return {
        type: "UserAgreement",
        version: "0.1",
        text: <>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam eu rhoncus dui, condimentum gravida velit. Pellentesque in rutrum leo, sed suscipit metus. Maecenas erat orci, malesuada vitae dui nec, congue convallis est. Integer vel ultrices nulla. Quisque tempus ligula at suscipit sodales. Integer pellentesque efficitur dui, sit amet mattis purus dapibus in. Phasellus auctor pellentesque urna, sed bibendum metus molestie ut. Fusce vulputate arcu in ligula finibus condimentum. Curabitur ante sapien, pellentesque et ornare consectetur, mattis et purus.</p>
                <p>Curabitur tellus metus, convallis sed sem non, dictum elementum mauris. Cras quis orci id ex posuere rhoncus. Suspendisse placerat ligula nec est rhoncus, et eleifend arcu egestas. Aenean varius nunc nisi, sit amet tincidunt orci ullamcorper vel. Donec semper orci non fermentum eleifend. Suspendisse at justo blandit massa porta malesuada. Quisque varius vulputate metus, eget pulvinar lorem ullamcorper vel. Aenean mollis fermentum libero, id imperdiet tellus accumsan nec. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla sit amet sem porttitor, consequat nunc eget, tempus leo. Cras sed turpis purus. Curabitur condimentum ipsum in sollicitudin sollicitudin.</p>
                <p>Nam condimentum imperdiet purus. Suspendisse vitae pharetra nisl. Sed eget diam augue. Mauris interdum ante a nisl feugiat tincidunt. Ut aliquet mi at nibh lobortis bibendum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nec eros augue. Proin imperdiet justo et diam tincidunt efficitur. Morbi vestibulum magna vitae nisi vestibulum dictum. Fusce at libero lobortis, lobortis arcu ac, convallis nisl. Donec consequat congue euismod. Fusce ut ex sit amet lectus ornare pellentesque non vel velit. Donec libero justo, tincidunt at orci a, gravida tincidunt eros.</p>
                <p>Donec sit amet arcu et lacus commodo finibus. Mauris vestibulum in eros sit amet luctus. Curabitur consequat porttitor finibus. Donec vitae ipsum vel nibh posuere facilisis sed non lectus. Cras at odio diam. Pellentesque aliquet egestas purus vitae ullamcorper. Praesent feugiat, ipsum non euismod condimentum, nulla mauris congue augue, a mattis nulla nisi eget massa. Integer ultricies sem sit amet laoreet convallis. Nam pellentesque dapibus eros, quis accumsan ex imperdiet sed. Nam eget dolor sit amet lacus semper laoreet.</p>
                <p>Nulla nec laoreet est. Vestibulum a vestibulum nisi. Donec imperdiet lorem ut urna porta, ut suscipit mi tempus. Nulla pellentesque tincidunt sem ut ornare. In imperdiet tellus quam, fermentum imperdiet diam maximus vel. In in sollicitudin ex. Quisque tortor justo, pulvinar vitae purus in, finibus vulputate ex. Donec eu ante vitae est semper feugiat quis eget erat. Mauris hendrerit ex neque, sed vestibulum leo tempus in. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque lacinia non risus a accumsan."</p>
            </>
    } as Agreement
}