name: e2e tests

on:
  #pull_request:
    #branches:
      #- main
  push:
    branches:
      - users/davidhayes03/code-rub-playwright

jobs:
    test:
        timeout-minutes: 60
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: lts/*
        - name: Install .Net
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 9.0.100-rc.2.24474.11
        - name: Install certificates
          run: dotnet dev-certs https --check --verbose
        - name: Restore
          run: dotnet restore
          working-directory: ./ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server
        - name: Build
          run: dotnet build --no-restore
          working-directory: ./ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Server
        - name: Install dependencies
          run: npm ci
          working-directory: ./ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client
        - name: Install Playwright Browsers
          run: npx playwright install --with-deps
          working-directory: ./ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client
        - name: Run Playwright tests
          working-directory: ./ISL.ReIdentification.WebApps.Portals/ISL.ReIdentification.Portals.Client
          run: npx playwright test
        - uses: actions/upload-artifact@v4
          if: ${{ !cancelled() }}
          with:
            name: playwright-report
            path: playwright-report/
            retention-days: 30
        env:
            TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
            TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}