name: Lint Codebase

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - users/dcunliffe/TS-Linting

jobs:
    lint:
        name: Linting
        runs-on: ubuntu-latest
        steps:
        - name:  Install NodeJS
          uses: actions/setup-node@v2
          with:
            node-version: 22
        - uses: actions/checkout@v2
        - name: Install modules
          working-directory: ./ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client
          run: npm install
        - name: Run ESLint
          working-directory: ./ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client
          run: npm run lint
        - name: Run JS Test
          working-directory: ./ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client
          run: npm run test
        - name: Run JS Build
          working-directory: ./ISL.ReIdentification.WebApps.Configurations/ISL.ReIdentification.Configurations.Client
          run: npm run build