name: PR Description Validation

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  validate-pr-description:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Get PR description
      id: get-pr
      uses: actions/github-script@v6
      with:
        script: |
          const pr = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.payload.pull_request.number
          });

          const prOwner = pr.data.user.login || "";
          const prBody = pr.data.body || "";
          core.setOutput("prOwner", prOwner);
          core.setOutput("description", prBody);

          console.log(`PR Owner: ${prOwner}`);
          console.log(`PR Body: ${prBody}`);

    - name: Normalize PR description and validate
      if: ${{ steps.get-pr.outputs.prOwner != 'dependabot[bot]' }}
      id: validate
      shell: bash
      run: |
        PR_BODY="${{ steps.get-pr.outputs.description }}"
    
        # Debug: Output the PR description
        echo "::notice::Raw PR Body: $PR_BODY"
    
        if [[ -z "$PR_BODY" ]]; then
          echo "Error: PR description does not contain any links to issue(s)/task(s) (e.g., 'closes #123' / 'closes AB#123' / 'fixes #123' / 'fixes AB#123')."
          exit 1
        fi
    
        # Normalize newlines and remove leading/trailing spaces
        PR_BODY=$(echo "$PR_BODY" | tr -s '\r\n' ' ' | tr '\n' ' ' | xargs)
    
        # Debug: Show PR body after normalization and trimming
        echo "::notice::Normalized PR Body: $PR_BODY"
    
        # Ensure the PR description matches the expected pattern
        if echo "$PR_BODY" | grep -Piq "((close|closes|closed|fix|fixes|fixed|resolve|resolves|resolved)\s*(\[#\d+\]|\#\d+)|(?:close|closes|closed|fix|fixes|fixed|resolve|resolves|resolved)\s*(\[AB#\d+\]|AB#\d+))"; then
          echo "Valid PR description."
        else
          echo "Error: PR description does not contain any links to issue(s)/task(s) (e.g., 'closes #123' / 'closes AB#123' / 'fixes #123' / 'fixes AB#123')."
          exit 1
        fi
