name: PR Description Validation

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  validate-pr-description:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Get PR description
      id: get-pr
      uses: actions/github-script@v6
      with:
        script: |
          const pr = context.payload.pull_request;
          if (!pr) {
            core.setFailed("This action can only run on pull requests.");
          }
          core.setOutput("description", pr.body || "");

    - name: Validate PR description
      id: validate
      shell: bash
      run: |
        # Capture the PR description
        PR_BODY="${{ steps.get-pr.outputs.description }}"
        
        # Debug: Output the PR description
        echo "PR Description: $PR_BODY"
        
        # Use grep to check for the required patterns
        echo "$PR_BODY" | grep -Eiq "closes\s*#\d+|closes\s*AB#\d+" || {
          echo "Error: PR description does not contain a closing issue/task link (e.g., 'closes #123' or 'closes AB#123')."
          exit 1
        }
