name: Validate PR Description

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  validate-description:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get PR information
      id: get-pr-info
      uses: actions-ecosystem/action-get-merged-pull-request@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Debug PR details
      run: |
        echo "PR Author: ${{ steps.get-pr-info.outputs.author }}"
        echo "PR Description: ${{ steps.get-pr-info.outputs.description }}"
    
    - name: Skip validation for dependabot
      id: check-dependabot
      run: |
        AUTHOR="${{ steps.get-pr-info.outputs.author }}"
        echo "AUTHOR=\"$AUTHOR\""
        if [[ "$AUTHOR" == "dependabot[bot]" ]]; then
          echo "PR was created by Dependabot. Skipping validation."
          exit 0
        fi

    - name: Validate PR description
      if: ${{ steps.get-pr-info.outputs.author != 'dependabot[bot]' }}
      id: validate
      shell: bash
      run: |
        # Capture the PR description and ensure safe handling of special characters
        PR_BODY=$(echo "${{ steps.get-pr-info.outputs.description }}" | jq -Rr @sh)

        # Debug: Output the PR description
        echo "::notice::Raw PR Body: \"$PR_BODY\""

        # Normalize newlines (\n and \r\n) by replacing them with a double space
        PR_BODY=$(echo "$PR_BODY" | tr -s '\r\n' '  ' | tr '\n' '  ')

        # Debug: Show PR body after normalization
        echo "::notice::Normalized PR Body: \"$PR_BODY\""

        # Use grep to check for the required patterns (with PCRE support)
        echo "$PR_BODY" | grep -Piq "(closes\s*\[#\d+\]|closes\s*\[AB#\d+\]|closes\s*#\d+|closes\s*AB#\d+|CLOSES\s*\[#\d+\]|CLOSES\s*\[AB#\d+\]|CLOSES\s*#\d+|CLOSES\s*AB#\d+)" || {
          echo "Error: PR description does not contain a closing issue/task link (e.g., 'closes #123' or 'closes AB#123')."
          exit 1
        }
